---
- name: Uninstall and remove NGINX
  hosts: webservers
  become: yes  # Escalate privileges to perform admin-level tasks
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Uninstall NGINX
      apt:
        name: nginx
        state: absent

    - name: Ensure NGINX is stopped and disabled 
      service:
        name: nginx
        state: stopped
        enabled: no
        
